"""
models.py — Core domain models for the OpenAPI Spec Crawler.

Design decisions:
- Pydantic v2 for runtime validation, serialization, and IDE support.
- Immutable history entries (frozen=True) to prevent accidental mutation.
- SpecStatus as a string enum so JSON serialization works without custom encoders.
- All timestamps are ISO-8601 strings (not datetime objects) to avoid tz-aware
  serialization edge cases in catalog persistence.
"""

from __future__ import annotations

from enum import Enum
from typing import Optional
from pydantic import BaseModel, Field, HttpUrl


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------

class SpecStatus(str, Enum):
    """Lifecycle status of a discovered spec within the catalog."""
    NEW = "new"
    UPDATED = "updated"
    UNCHANGED = "unchanged"
    ERROR = "error"


class OpenAPIVersion(str, Enum):
    """Broad version family detected from the spec document."""
    SWAGGER_2 = "swagger_2"
    OPENAPI_3 = "openapi_3"
    UNKNOWN = "unknown"


# ---------------------------------------------------------------------------
# Parsed spec data
# ---------------------------------------------------------------------------

class ParsedSpec(BaseModel):
    """
    Structured data extracted from a raw OpenAPI/Swagger document.

    Fields intentionally use Optional so the parser can return a partial
    result when a spec is malformed rather than raising.
    """
    title: Optional[str] = None
    version: Optional[str] = None
    description: Optional[str] = None
    openapi_version: OpenAPIVersion = OpenAPIVersion.UNKNOWN
    servers: list[str] = Field(default_factory=list)
    tags: list[str] = Field(default_factory=list)
    paths_count: int = 0
    raw_paths: list[str] = Field(default_factory=list)  # for diff generation

    # Parse health
    parse_error: Optional[str] = None
    is_valid: bool = True


# ---------------------------------------------------------------------------
# Version diff (generated by versioning module)
# ---------------------------------------------------------------------------

class PathDiff(BaseModel):
    """
    Describes path-level changes between two spec versions.

    Kept separate from HistoryEntry so it can be computed lazily.
    """
    added: list[str] = Field(default_factory=list)
    removed: list[str] = Field(default_factory=list)

    @property
    def has_changes(self) -> bool:
        return bool(self.added or self.removed)


# ---------------------------------------------------------------------------
# History entry (immutable record of a single crawl snapshot)
# ---------------------------------------------------------------------------

class HistoryEntry(BaseModel, frozen=True):
    """
    Immutable snapshot of a spec at the moment it was fetched.

    frozen=True enforces immutability at the Pydantic level — no field
    can be reassigned after construction.  History files are written once
    and never modified; this model reflects that contract in code.
    """
    spec_id: str                        # stable identifier (SHA of URL)
    source_url: str
    fetched_at: str                     # ISO-8601 UTC
    content_hash: str                   # SHA-256 of raw file bytes
    info_version: Optional[str]         # value of info.version in the spec
    status: SpecStatus
    title: Optional[str]
    openapi_version: OpenAPIVersion
    paths_count: int
    path_diff: Optional[PathDiff] = None  # None for NEW entries


# ---------------------------------------------------------------------------
# Catalog entry (mutable — updated on each crawl run)
# ---------------------------------------------------------------------------

class CatalogEntry(BaseModel):
    """
    The live record for a spec stored in catalog.json.

    Mutable between runs; history_file points to the sidecar file that
    holds all historical snapshots for this spec.
    """
    spec_id: str
    source_url: str
    title: Optional[str] = None
    description: Optional[str] = None
    openapi_version: OpenAPIVersion = OpenAPIVersion.UNKNOWN
    servers: list[str] = Field(default_factory=list)
    tags: list[str] = Field(default_factory=list)
    paths_count: int = 0

    # Version tracking
    latest_info_version: Optional[str] = None
    latest_hash: Optional[str] = None
    status: SpecStatus = SpecStatus.NEW
    first_seen_at: str = ""
    last_updated_at: str = ""
    fetched_at: str = ""

    # Sidecar
    history_file: str = ""              # relative path under data/history/


# ---------------------------------------------------------------------------
# Crawl run summary (emitted as a structured log event)
# ---------------------------------------------------------------------------

class CrawlStats(BaseModel):
    """Aggregate statistics for a single crawler run."""
    run_id: str
    started_at: str
    finished_at: str = ""
    total_discovered: int = 0
    total_fetched: int = 0
    total_parsed: int = 0
    new_specs: int = 0
    updated_specs: int = 0
    unchanged_specs: int = 0
    error_specs: int = 0
    duration_seconds: float = 0.0